{{- $globals := ternary .Values.global.prod .Values.global.dev (eq .Values.global.env_name "prod") -}}
apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque
data:
  mysqlUser: {{ $globals.mysql.user | b64enc }}
  mysqlPassword: {{ $globals.mysql.password | b64enc }}
  {{- if ne .Values.global.env_name "prod" }}
  mysqlProdCopyUser: {{ $globals.mysql.prodCopy.user | b64enc }}
  mysqlProdCopyPassword: {{ $globals.mysql.prodCopy.password | b64enc }}
  {{- end}}
  appKey: {{ $globals.app.key | b64enc }}
  s3AccessKey: {{ $globals.s3.accessKey | b64enc }}
  s3SecretKey: {{ $globals.s3.secretKey | b64enc }}
  {{- if ne .Values.global.env_name "prod" }}
  mysqlRootPassword: {{ $globals.mysql.rootPassword | b64enc }}
  {{- end }}
---
