apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    {{- if ne .Values.global.mon_probe "" }}
    synergy.ru/blackbox.probe: {{ .Values.global.mon_probe }}
    {{- end }}
    {{- if ne .Values.global.mon_code "" }}
    synergy.ru/blackbox.code: {{ .Values.global.mon_code }}
    {{- end }}
    kubernetes.io/ingress.class: "nginx"
    {{- if ne .Values.global.www_redirect "no" }}
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    {{- end }}
    {{- if eq .Values.global.env_name "dev" }}
    nginx.ingress.kubernetes.io/auth-url: "http://dev-auth.auth.svc.cluster.local"
    {{- end }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      # Additional configuration snippet
      {{- if ne (.Values.block_code|default "") "" }}
      {{- range $index, $country := .Values.block_countries }}
      if ($geoip2_city_country_code = {{ $country.code }}) {
        return {{ $.Values.block_code }};
      }
      {{- end }}
      {{- end }}

      {{- if and (ne .Values.global.ci_path "") (ne .Values.global.ci_path "/") }}
      #rewrite ^([^.]*[^/])$ $1/ permanent;
      rewrite (?i)/{{ .Values.global.ci_path | trimAll "/" }}(/|$)(.*) /$2 break;
      {{- end }}
  name: ingress
spec:
  rules:
      - host: {{ .Values.global.ci_url }}
        http:
          paths:
          - backend:
              service:
                name: {{ .Values.global.app_name }}
                port: 
                  number: 80
            pathType: Prefix
            {{- if and (ne .Values.global.ci_path "") (ne .Values.global.ci_path "/") }}
            path: /{{ .Values.global.ci_path | trimAll "/" }}
            {{- else }}
            path: /
            {{- end }}
---
