global:
  app_name: marketplace-api

  dev:
    app:
      debug: "true"
      key: "MaHw5tDnFkGbtZyjydBoYBWnzCuxbBgI"

    s3:
      endpoint: https://dev.sys3.ru
      bucket: marketplace

    mysql:
      host: mysql
      port: "3306"
      rootPassword: NH8F4Dj2TShv4uYq1tUSnI1b
      user: marketplace
      password: O7csEBBqu9a6ZaKauiuJ41SN
      database: marketplace

    log:
      host: syslog2.synergy.ru
      port: "12201"

    mail:
      host: mail.default
      port: "25"

    elasticsearch:
      url: http://msk1-es31.synergy.local:9200

  prod:
    app:
      debug: "true"

    s3:
      endpoint: https://sys3.ru
      bucket: marketplace

    mysql:
      host: msk1-kdb12.synergy.local
      port: "3306"
      database: marketplace

    log:
      host: syslog.synergy.ru
      port: "12201"

    mail:
      host: mail.default
      port: "25"

    elasticsearch:
      url: http://msk1-es21.synergy.local:9200
